### ISSUE TITLE
Performance comparison with WMI

### ISSUE THREAD

**Issue by carlpett** [carlpett/winlsa#1]
The immediate motivation for this package is improved performance vs using WMI to read logon sessions. I do not however have a busy enough server to validate that it is actually so.

@frittentheke @fdcastel since you discussed this in [windows_exporter #89](https://github.com/prometheus-community/windows_exporter/issues/89), would you be willing to test running cmd/demo in this repo on one of your machines to see how long time it takes? 
Let me know if you want precompiled binaries.

**Comment by frittentheke** [comment]
@carlpett certainly.

**Comment by frittentheke** [comment]
@carlpett  very sorry for the delay. I now ran the demo on the Exchange machine ...

```
Measure-Command -Expression {.\demo.exe}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 178
Ticks             : 1789719
TotalDays         : 2,07143402777778E-06
TotalHours        : 4,97144166666667E-05
TotalMinutes      : 0,002982865
TotalSeconds      : 0,1789719
TotalMilliseconds : 178,9719

```

as we are a bit out of the prime time usage on that machine now, so I shall rerun this tomorrow.
But first impression is that it's much much snappier - even when run multiple times in rapid succession.

**Comment by frittentheke** [comment]
@carlpett I now ran the command again during the morning rush of people fetching their emails and the performance looks almost identical to last night:

```
Measure-Command -Expression {.\demo.exe}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 249
Ticks             : 2493910
TotalDays         : 2,88646990740741E-06
TotalHours        : 6,92752777777778E-05
TotalMinutes      : 0,00415651666666667
TotalSeconds      : 0,249391
TotalMilliseconds : 249,391
```

The duration for a single invocation moves between 150 and 350ms with no apparent spikes or hickups.

**Comment by carlpett** [comment]
Thanks! If we're at a 15-20x speedup, it sounds like it'd make a lot of sense to swap out the logon collector to use this, then :)
